#!/bin/bash

set -e

DEFAULT_CNT="rpi-shairport-sync"

CMD=$1
CNT=$2

if [ -z "$CMD" ]; then
    echo "Please specify a command (start|stop|status|build|clean)."
    exit 1
fi

if [ -z "$CNT" ]; then
    CNT=$DEFAULT_CNT
fi

CMD_STOP="docker stop $(docker ps -aq --filter=[name=$CNT])"
CMD_STATUS="docker ps"

CMD_BUILD="docker build -t $CNT-build ./build"
CMD_BUILD_RUN="docker run --rm=true -v $(pwd)/dist:/build $CNT-build"
CMD_BUILD_DIST="docker build -t $CNT ./dist"
CMD_CLEAN="docker rm -f $CNT-build"
CMD_CLEAN_IMG="docker rmi $CNT-build"

case "$CMD" in
    start )
        docker run -d \
            -e ARGS="-a 'Media Player' -w -B '/controller -c=client.conf.json -m=EVT\ shairport:PLAY:START' -E '/controller -c=client.conf.json -m=EVT\ shairport:PLAY:STOP'" \
            --net=host \
            --device=/dev/snd/controlC0:/dev/snd/controlC0 \
            --device=/dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p \
            --device=/dev/snd/pcmC0D1p:/dev/snd/pcmC0D1p \
            --device=/dev/snd/seq:/dev/snd/seq \
            --device=/dev/snd/timer:/dev/snd/timer \
            $CNT
        ;;
    stop )
         $CMD_STOP ;;
    build )
         $CMD_BUILD && \
         $CMD_BUILD_RUN && \
         $CMD_BUILD_DIST ;;
    clean )
        $CMD_CLEAN 2> /dev/null ; \
        $CMD_CLEAN_IMG ;;
    status )
         $CMD_STATUS | grep $CNT || echo "Not running" ;;
esac
